"""GR00T N1.6 modality config for the LIBERO Franka *task-space* embodiment,
RELATIVE end-effector variant (xyz + rotvec).

This is the relative-action counterpart of `libero_franka_task_space_n16_config.py`.
It targets the dataset produced by `convert_task_space_quat_to_rotvec.py`, whose
state/action are 7-dim:
    state  = franka_eef_pose(0:6) + franka_gripper_pos(6:7)
    action = franka_eef_pose(0:6) + franka_gripper_pos(6:7)
where `franka_eef_pose` is [xyz(3), rotvec(3)] (compact axis-angle).

Design choice (relative EEF pose, absolute gripper):
- The EEF pose is combined into a single 6-dim key and configured as
  ActionType.EEF + ActionFormat.XYZ_ROTVEC + ActionRepresentation.RELATIVE,
  with `state_key="franka_eef_pose"`. At load time the processor converts each
  absolute pose in the action chunk into a transform relative to the *last*
  state pose (reference frame), via homogeneous matrices. This requires
  `meta/relative_stats.json` (generated by `gr00t/data/stats.py`).
- The gripper stays ABSOLUTE + NON_EEF (min/max normalized).
- `use_relative_action` is hard-enabled in `gr00t/experiment/launch_finetune.py`
  (config.model.use_relative_action = True), so relative conversion is active in
  both training and inference.

Usage (register under NEW_EMBODIMENT, per the N1.6 custom-embodiment workflow):
    --embodiment-tag NEW_EMBODIMENT \
    --modality-config-path <this file>
"""

from gr00t.configs.data.embodiment_configs import register_modality_config
from gr00t.data.embodiment_tags import EmbodimentTag
from gr00t.data.types import (
    ActionConfig,
    ActionFormat,
    ActionRepresentation,
    ActionType,
    ModalityConfig,
)


libero_franka_task_space_rel_config = {
    "video": ModalityConfig(
        delta_indices=[0],
        modality_keys=[
            "agentview_cam",
            "eye_in_hand_cam",
        ],
    ),
    "state": ModalityConfig(
        delta_indices=[0],
        modality_keys=[
            "franka_eef_pose",
            "franka_gripper_pos",
        ],
    ),
    "action": ModalityConfig(
        delta_indices=list(range(16)),
        modality_keys=[
            "franka_eef_pose",
            "franka_gripper_pos",
        ],
        action_configs=[
            # franka_eef_pose: relative EEF pose in xyz+rotvec format.
            ActionConfig(
                rep=ActionRepresentation.RELATIVE,
                type=ActionType.EEF,
                format=ActionFormat.XYZ_ROTVEC,
                state_key="franka_eef_pose",
            ),
            # franka_gripper_pos: absolute gripper command.
            ActionConfig(
                rep=ActionRepresentation.ABSOLUTE,
                type=ActionType.NON_EEF,
                format=ActionFormat.DEFAULT,
            ),
        ],
    ),
    "language": ModalityConfig(
        delta_indices=[0],
        modality_keys=["annotation.human.action.task_description"],
    ),
}

register_modality_config(
    libero_franka_task_space_rel_config, embodiment_tag=EmbodimentTag.NEW_EMBODIMENT
)
